version: 0.2

           

phases:

  install:

    runtime-versions:

      java: corretto17

    commands:

      - echo install

  pre_build:

    commands:

      - echo pre_build

  build:

    commands:

      - mvn package

      - echo build

  post_build:
    commands:
      - echo Build completed on `date`
      - mv target/spring-boot-web-application-h2-0.0.1-SNAPSHOT.war ROOT.war
artifacts:
  files:
    - ROOT.war
